#!/usr/bin/env zsh

re='^[0-9]{4}$'

while getopts vp: option; do
    case "${option}" in
        v ) 
            VERBOSE="vv"
            ;;
        p ) 
            if [[ ${OPTARG} =~ $re ]]
            then
                PORT=${OPTARG}
            else
                echo "Invalid Argument (PORT)"
            fi
            ;;
    esac
done

if [[ -z $PORT ]]; then
    PORT=8000
    echo "Missing Argument (PORT), run on 8000 by default"
fi

if [[ -e ./app/console ]]
then
    `php app/console --ansi server:run 127.0.0.1:$PORT -v$VERBOSE`
elif [[ -e ./bin/console ]]
then
    if [[ -x "$(command -v symfony)" ]]
    then
        `symfony server:start --port=$PORT`
    else
        `php bin/console --ansi server:run 127.0.0.1:$PORT -v$VERBOSE`
    fi
else
    echo "Not in a symfony project root, do you want to launch a php server ? [y/n]"
    read answer
    
    case $answer in
        'y')
            echo 'launch php server'
            `php -S 127.0.0.1:$PORT`
            ;;
        'n')
            echo 'exit'
            exit
            ;;
        *)
            echo 'Wrong answer, do you want to launch a php server ? [y/n]'
            read answer
    esac
fi

exit
